# -----------------------------------------------------------------------
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
# -----------------------------------------------------------------------

jakeocc.webroot=/jakeocc_junit
jakeocc.security.config=config/test-security-spring.xml
jakeocc.ehcache.location=/WEB-INF/cache/junit_ehcache.xml